# Generated by Django 4.0.4 on 2022-04-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Tipo',
        ),
    ]
