# Generated by Django 4.0.4 on 2022-04-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_type_pokedex_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='base_stats',
            field=models.ImageField(upload_to='pokemons/covers/%y/%m/%d'),
        ),
    ]
