# Generated by Django 4.0.4 on 2022-04-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pokedex_base_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokedex',
            old_name='pokemon_type',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='cover',
            field=models.ImageField(blank=True, upload_to='pokemons/covers/%y/%m/%d'),
        ),
    ]
