# Generated by Django 4.0.4 on 2022-05-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_pokemon_type_pokedex_tipo_alter_pokedex_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='pokemons/covers/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='tipo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipo'),
        ),
    ]
