# Generated by Django 4.0.4 on 2022-05-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pokedex_cover_alter_pokedex_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_2', models.CharField(max_length=65)),
            ],
        ),
        migrations.AddField(
            model_name='pokedex',
            name='tipo_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipo_2'),
        ),
    ]
